# Generated by Django 5.1.1 on 2024-09-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_carro'),
        ('lavagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavagem',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.carro'),
            preserve_default=False,
        ),
    ]
