# Generated by Django 6.0.3 on 2026-03-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_alter_carro_cliente_alter_carro_nome_and_more'),
        ('cliente', '0006_remove_carro_cliente'),
        ('lavagem', '0002_lavagem_carro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lavagem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lavagens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lavagem',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavagens', to='carro.carro'),
        ),
        migrations.AlterField(
            model_name='lavagem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavagens', to='cliente.cliente'),
        ),
    ]
