# Generated by Django 6.0.3 on 2026-03-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='cliente',
        ),
    ]
