# Generated by Django 6.0.3 on 2026-03-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_carro_cliente'),
        ('lavagem', '0003_lavagem_user_alter_lavagem_carro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
