# Generated by Django 5.1.1 on 2024-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
