# Generated by Django 5.1.1 on 2024-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_alter_carro_cliente_carro_user_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
