# Generated by Django 6.0.3 on 2026-03-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_carro_nome'),
        ('cliente', '0005_carro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to=settings.AUTH_USER_MODEL),
        ),
    ]
